### ISSUE TITLE
Error: A silent sign-in request was sent but no user is signed in.

### ISSUE THREAD

**Issue by AElharouny** [Azure/ms-rest-browserauth#31] opened 2020-08-30 01:52 UTC
Hello,

First time I log-in all good. When I close browser and reopen after  few hours I start to get this error:

```
AADSTS50058: A silent sign-in request was sent but no user is signed in.
```

![image](https://user-images.githubusercontent.com/52023187/91649375-b895e480-eab6-11ea-968d-76a28430b301.png)

The problem is the error happens in the constructor of `AuthManager` causing the app to fail.

FYI when I log in I click "Keep Me Signed In"

My code:
``` javascript
  componentDidMount(){
    this.authManager = new AuthManager({ clientId: process.env.REACT_APP_AAD_APP_CLIENT_ID, tenant: process.env.REACT_APP_AAD_APP_TENANT_ID });
    this.authManager.finalizeLogin()
    .then(result => {
      if (result.isLoggedIn) {
        //
      } else {
        //
      }
    });
  }

  onLoginButtonClick(){
    if (this.state.isLoggedIn) {
      this.authManager.logout();
    } else {
      this.authManager.login();
    }
  }
```

**Comment by sadasant** [comment] 2021-01-25 21:45
@AElharouny

Hello hello! Although very delayed, I wanted to see if I could still help you. Are you still having this issue?

I believe the issue is caused because the token hasn't been refreshed in a while. The best way to overcome this, specially for the case of closing and re-opening the browser, is to catch the error and retry the login. How does that sound?

We're actively working on a new package: https://www.npmjs.com/package/@azure/identity

Let me know if you are able to find the time or if it's possible for you to switch to that new package. We'll be able to provide a faster and better response over there.

Thank you for your time submitting this issue! I'll be able to answer faster at this point. I'm looking forward for your response!

Take care,
Daniel.

**Comment by sadasant** [comment] 2021-01-26 19:11
@AElharouny a quick follow up, please read this!

What Azure SDK client are you working with?

Not all of the available clients work with the new @azure/identity package yet. Please check the README of the client you're working with to see if it's explicitly stated that this client supports `@azure/identity`. They will either mention they work with `@azure/identity`, or with `ms-rest-nodeauth` and `ms-rest-browserauth`.

Thank you again for your time!

**Comment by AElharouny** [comment] 2021-01-26 22:50
I think I handled that error by catching it and showing the login button for users to login again. I'm using a client that still works with `ms-rest-browserauth` last time I checked at least: `@azure/arm-servicebus` .

**Comment by sadasant** [comment] 2021-01-30 01:14
@AElharouny that sounds like a good approach! We'll be providing a better experience in the future. Is there anything else I can help you with?

**Comment by AElharouny** [comment] 2021-01-30 02:04
No all good now. Thanks.

**Closed** 2021-02-01 17:58 UTC
